export const ALL_PRODUCTS = [
  {
    id: 1,
    name: "Elegant Leather Watch",
    category: "watches",
    price: 15999,
    image: "/elegant-leather-watch.jpg",
    rating: 4.8,
    reviews: 124,
    badge: "New",
    description: "A timeless leather watch perfect for any occasion",
  },
  {
    id: 2,
    name: "Classic Brown Shoulder Bag",
    category: "bags",
    price: 8999,
    image: "/brown-leather-bag.jpg",
    rating: 4.6,
    reviews: 89,
    badge: "Popular",
    description: "Stylish shoulder bag crafted from premium brown leather",
  },
  {
    id: 3,
    name: "Digital Smart Watch",
    category: "watches",
    price: 18999,
    image: "/smart-watch-digital.jpg",
    rating: 4.9,
    reviews: 156,
    badge: "Best Seller",
    description: "Advanced digital smart watch with health tracking",
  },
  {
    id: 4,
    name: "Elegant Crossbody Bag",
    category: "bags",
    price: 12999,
    image: "/stylish-crossbody-bag.png",
    rating: 4.7,
    reviews: 98,
    description: "Versatile crossbody bag for everyday use",
  },
  {
    id: 5,
    name: "Chronograph Steel Watch",
    category: "watches",
    price: 22999,
    image: "/chronograph-steel-watch.jpg",
    rating: 4.9,
    reviews: 167,
    badge: "Luxury",
    description: "Luxury chronograph with steel craftsmanship",
  },
  {
    id: 6,
    name: "Premium Tote Bag",
    category: "bags",
    price: 11999,
    image: "/premium-tote-bag.jpg",
    rating: 4.8,
    reviews: 112,
    description: "Large capacity tote bag for professionals",
  },
  {
    id: 7,
    name: "Vintage Dial Watch",
    category: "watches",
    price: 13999,
    image: "/vintage-dial-watch.jpg",
    rating: 4.7,
    reviews: 95,
    description: "Classic vintage-inspired dial design",
  },
  {
    id: 8,
    name: "Minimalist Backpack",
    category: "bags",
    price: 9999,
    image: "/minimalist-backpack.png",
    rating: 4.5,
    reviews: 67,
    description: "Modern minimalist backpack design",
  },
  {
    id: 9,
    name: "Rose Gold Watch",
    category: "watches",
    price: 19999,
    image: "/rose-gold-watch.jpg",
    rating: 4.8,
    reviews: 134,
    description: "Elegant rose gold timepiece",
  },
  {
    id: 10,
    name: "Leather Clutch",
    category: "bags",
    price: 7999,
    image: "/leather-clutch.jpg",
    rating: 4.6,
    reviews: 76,
    description: "Stylish clutch for evening events",
  },
  {
    id: 11,
    name: "Sports Watch",
    category: "watches",
    price: 16999,
    image: "/sports-watch.jpg",
    rating: 4.7,
    reviews: 102,
    description: "Water-resistant sports watch",
  },
  {
    id: 12,
    name: "Travel Luggage Bag",
    category: "bags",
    price: 14999,
    image: "/travel-luggage-bag.jpg",
    rating: 4.9,
    reviews: 128,
    description: "Durable travel luggage with organization",
  },
]

export const ITEMS_PER_PAGE = 6
